# Holt das L3-NER-Modell + Tokenizer + ONNX-Runtime-DLL.
#
# Modell: Xenova/distilbert-base-multilingual-cased-ner-hrl (ONNX-Port
# von Davlan/distilbert-base-multilingual-cased-ner-hrl, Apache-2.0).
# Multilinguales DistilBERT mit NER-Head, 9 Labels (O + B/I für DATE,
# PER, ORG, LOC). INT8-quantisiert ~129 MB.
#
# **Supply-Chain-Hinweis:** Xenova ist ein etablierter Community-
# Maintainer (transformers.js), aber kein HF-„Verified"-Account. Wir
# pinnen die SHA-256-Hashes aller Files in MANIFEST.sha256 — sobald
# die Phase-B-Härtung greift (siehe src-tauri/models/README.md), wird
# das Modell aus einem eigenen Mirror gezogen und der Hash signiert.
#
# Ziel-Layout:
#   src-tauri/models/model.onnx        — quantisiertes ONNX-Modell
#   src-tauri/models/tokenizer.json    — HF-Tokenizer
#   src-tauri/models/MANIFEST.sha256   — Hash-Manifest (Runtime-Check)
#   src-tauri/models/onnxruntime.dll   — ORT-Runtime (lädt zur Laufzeit)
#
# Verwendung:
#   powershell -ExecutionPolicy Bypass -File scripts/download-ner-model.ps1
#
# Voraussetzung: PowerShell 5+ und Internet-Zugang. Lädt direkt von
# huggingface.co und github.com/microsoft/onnxruntime.

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$modelsDir = Join-Path $repoRoot 'src-tauri\models'
New-Item -ItemType Directory -Force -Path $modelsDir | Out-Null

# Davlan-Repo selbst hat KEIN onnx/-Verzeichnis. Xenova mirrort die
# Optimum-Konvertierung — siehe Supply-Chain-Hinweis oben.
$modelUrl = 'https://huggingface.co/Xenova/distilbert-base-multilingual-cased-ner-hrl/resolve/main/onnx/model_quantized.onnx'
$tokenizerUrl = 'https://huggingface.co/Xenova/distilbert-base-multilingual-cased-ner-hrl/resolve/main/tokenizer.json'

# ONNX-Runtime 1.22.x. **Wichtig:** das `ort = 2.0.0-rc.10` Crate
# verifiziert beim Start die DLL-Version via `GetVersionString` und
# erwartet exakt `1.22.x`. Andere Versionen → Rust-Panic.
# Bei Crate-Upgrade die hier gesetzte Version entsprechend anpassen.
$ortVersion = '1.22.0'
$ortUrl = "https://github.com/microsoft/onnxruntime/releases/download/v$ortVersion/onnxruntime-win-x64-$ortVersion.zip"

function Get-File($url, $dest) {
    Write-Host "  → $url"
    Invoke-WebRequest -Uri $url -OutFile $dest -UseBasicParsing
    $size = (Get-Item $dest).Length / 1MB
    Write-Host ("    OK ({0:N1} MB)" -f $size)
}

Write-Host 'Downloading NER model...'
Get-File $modelUrl (Join-Path $modelsDir 'model.onnx')

Write-Host 'Downloading tokenizer...'
Get-File $tokenizerUrl (Join-Path $modelsDir 'tokenizer.json')

Write-Host 'Downloading ONNX Runtime...'
$ortZip = Join-Path $env:TEMP 'ort.zip'
Get-File $ortUrl $ortZip
$ortExtract = Join-Path $env:TEMP 'ort-extract'
if (Test-Path $ortExtract) { Remove-Item -Recurse -Force $ortExtract }
Expand-Archive -Path $ortZip -DestinationPath $ortExtract
$dll = Get-ChildItem -Path $ortExtract -Filter 'onnxruntime.dll' -Recurse | Select-Object -First 1
if (-not $dll) {
    throw 'onnxruntime.dll nicht im Archiv gefunden — URL geändert?'
}
Copy-Item $dll.FullName -Destination (Join-Path $modelsDir 'onnxruntime.dll')
Write-Host '    onnxruntime.dll bereitgestellt'

# MANIFEST.sha256 erzeugen — wird zur Laufzeit vom NER-Loader gegen die
# tatsächlichen Hashes der Files geprüft (Supply-Chain-Schutz).
Write-Host 'Generating MANIFEST.sha256...'
$manifestPath = Join-Path $modelsDir 'MANIFEST.sha256'
$manifestLines = @(
    '# Auto-generated by scripts/download-ner-model.ps1.',
    '# Format: <sha256-hex>  <relative-path>',
    '# Manuelle Edits sind ok, müssen aber synchron zu den Dateien bleiben.'
)
foreach ($name in @('model.onnx', 'tokenizer.json')) {
    $p = Join-Path $modelsDir $name
    $hash = (Get-FileHash -Algorithm SHA256 -Path $p).Hash.ToLower()
    $manifestLines += "$hash  $name"
}
Set-Content -Path $manifestPath -Value $manifestLines -Encoding utf8
Write-Host "    MANIFEST.sha256 geschrieben ($($manifestLines.Count) Zeilen)"

Write-Host ''
Write-Host 'Fertig. Build mit:'
Write-Host '    cd src-tauri'
Write-Host '    cargo build --features ner'
Write-Host ''
Write-Host 'Im laufenden Build die DLL nach target/debug/ kopieren, damit'
Write-Host 'sie neben der EXE liegt:'
Write-Host '    Copy-Item src-tauri\models\onnxruntime.dll src-tauri\target\debug\'
