#!/usr/bin/env bash
# Holt das L3-NER-Modell + Tokenizer + ONNX-Runtime-Dylib (macOS/Linux).
#
# Modell: Xenova/distilbert-base-multilingual-cased-ner-hrl
# (ONNX-Port von Davlan-Original, Apache-2.0, ~129 MB INT8).
# Supply-Chain-Härtung siehe src-tauri/models/README.md.
#
# Ziel-Layout:
#   src-tauri/models/model.onnx           — quantisiertes ONNX-Modell
#   src-tauri/models/tokenizer.json       — HF-Tokenizer
#   src-tauri/models/MANIFEST.sha256      — Hash-Manifest (Runtime-Check)
#   src-tauri/models/libonnxruntime.dylib — ORT-Runtime
#
# Verwendung:
#   bash scripts/download-ner-model.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MODELS_DIR="$REPO_ROOT/src-tauri/models"
mkdir -p "$MODELS_DIR"

MODEL_URL="https://huggingface.co/Xenova/distilbert-base-multilingual-cased-ner-hrl/resolve/main/onnx/model_quantized.onnx"
TOKENIZER_URL="https://huggingface.co/Xenova/distilbert-base-multilingual-cased-ner-hrl/resolve/main/tokenizer.json"

# ORT 1.22.x — Crate ort=2.0.0-rc.10 prüft DLL-Version und erwartet 1.22.x.
ORT_VERSION="1.22.0"
case "$(uname -s)" in
  Darwin)
    case "$(uname -m)" in
      arm64)  ORT_ASSET="onnxruntime-osx-arm64-${ORT_VERSION}.tgz" ;;
      x86_64) ORT_ASSET="onnxruntime-osx-x86_64-${ORT_VERSION}.tgz" ;;
      *) echo "Unbekannte macOS-Architektur: $(uname -m)"; exit 1 ;;
    esac
    DYLIB_NAME="libonnxruntime.dylib"
    ;;
  Linux)
    ORT_ASSET="onnxruntime-linux-x64-${ORT_VERSION}.tgz"
    DYLIB_NAME="libonnxruntime.so"
    ;;
  *) echo "Unsupported OS: $(uname -s)"; exit 1 ;;
esac

ORT_URL="https://github.com/microsoft/onnxruntime/releases/download/v${ORT_VERSION}/${ORT_ASSET}"

fetch() {
  echo "  → $1"
  curl -L --fail --silent --show-error --output "$2" "$1"
  size=$(du -h "$2" | cut -f1)
  echo "    OK ($size)"
}

echo "Downloading NER model..."
fetch "$MODEL_URL" "$MODELS_DIR/model.onnx"

echo "Downloading tokenizer..."
fetch "$TOKENIZER_URL" "$MODELS_DIR/tokenizer.json"

echo "Downloading ONNX Runtime..."
TMP_TAR="$(mktemp)"
fetch "$ORT_URL" "$TMP_TAR"
TMP_DIR="$(mktemp -d)"
tar -xzf "$TMP_TAR" -C "$TMP_DIR"
DYLIB_PATH="$(find "$TMP_DIR" -name "$DYLIB_NAME" | head -n 1)"
if [ -z "$DYLIB_PATH" ]; then
  echo "$DYLIB_NAME nicht im Archiv gefunden — URL geändert?" >&2
  exit 1
fi
cp "$DYLIB_PATH" "$MODELS_DIR/$DYLIB_NAME"
echo "    $DYLIB_NAME bereitgestellt"
rm -rf "$TMP_TAR" "$TMP_DIR"

# Win-DLL-Placeholder für plattform-übergreifenden `tauri build`.
# Unser tauri.conf.json hat `bundle.resources["models/onnxruntime.dll"]`
# eingetragen (für den Windows-MSI-Bundler). Auf Mac/Linux würde der
# Tauri-Build sonst mit „file not found" fehlschlagen, weil die Datei
# nicht existiert. Eine leere Placeholder-Datei reicht — sie landet
# zwar mit ins App-Bundle (~0 Byte Bloat), wird aber niemals geladen
# (Mac nutzt die libonnxruntime.dylib direkt neben der EXE über
# `bundle.macOS.files`).
if [ ! -f "$MODELS_DIR/onnxruntime.dll" ]; then
  touch "$MODELS_DIR/onnxruntime.dll"
  echo "    onnxruntime.dll placeholder erstellt (für plattformübergreifenden Build)"
fi

# MANIFEST.sha256 erzeugen — wird zur Laufzeit vom NER-Loader gegen die
# tatsächlichen Hashes der Files geprüft (Supply-Chain-Schutz).
echo "Generating MANIFEST.sha256..."
MANIFEST="$MODELS_DIR/MANIFEST.sha256"
{
  echo "# Auto-generated by scripts/download-ner-model.sh."
  echo "# Format: <sha256-hex>  <relative-path>"
  echo "# Manuelle Edits sind ok, müssen aber synchron zu den Dateien bleiben."
  for name in model.onnx tokenizer.json; do
    if command -v sha256sum >/dev/null 2>&1; then
      sha256=$(sha256sum "$MODELS_DIR/$name" | awk '{print $1}')
    else
      # macOS hat sha256sum nicht standardmäßig, dafür shasum.
      sha256=$(shasum -a 256 "$MODELS_DIR/$name" | awk '{print $1}')
    fi
    echo "$sha256  $name"
  done
} > "$MANIFEST"
echo "    MANIFEST.sha256 geschrieben"

echo
echo "Fertig. Build mit:"
echo "    cd src-tauri"
echo "    cargo build --features ner"
echo
echo "Beim Run muss $DYLIB_NAME neben der EXE liegen:"
echo "    cp src-tauri/models/$DYLIB_NAME src-tauri/target/debug/"
